apiVersion: v2
name: mlflow
description: A Helm chart for Mlflow open source platform for the machine learning lifecycle

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

version: 1.0.4

appVersion: ""

kubeVersion: ">=1.16.0-0"

home: https://mlflow.org

maintainers:
  - name: burakince
    email: burak.ince@linux.org.tr
    url: https://www.burakince.net

sources:
  - https://github.com/community-charts/helm-charts
  - https://github.com/burakince/mlflow
  - https://github.com/mlflow/mlflow

dependencies: []
