{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-env-secret
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.backendStore.postgres.enabled }}
  {{- range  $key, $value := .Values.secrets }}
  {{$key }}: {{ $value | quote | b64enc }}
  {{- end }}
  {{- end }}
{{- if .Values.backendStore.mysql.enabled }}
  {{- range  $key, $value := .Values.secrets }}
  {{$key }}: {{ $value | quote | b64enc }}
  {{- end }}
  {{- end }}
{{- if .Values.artifactRoot.azureBlob.enabled }}
{{- if .Values.artifactRoot.azureBlob.connectionString }}
  {{- range  $key, $value := .Values.secrets }}
  {{$key }}: {{ $value | quote | b64enc }}
  {{- end }}
  {{- end }}
{{- if .Values.artifactRoot.azureBlob.accessKey }}
  {{- range  $key, $value := .Values.secrets }}
  {{$key }}: {{ $value | quote | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.artifactRoot.s3.enabled }}
{{- if and .Values.artifactRoot.s3.awsAccessKeyId .Values.artifactRoot.s3.awsSecretAccessKey }}
  {{- range  $key, $value := .Values.secrets }}
  {{$key }}: {{ $value | quote | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
